name       : libebml
version    : 1.3.3
release    : 1
source     :
    - http://dl.matroska.org/downloads/libebml/libebml-1.3.3.tar.bz2 : 35fb44daa41961f94a0ac1b8f06801e88cc9bf2ad6f562ced8ab7c1f1a875499
license    : LGPL-2.1
summary    : libeml
description: |
    a C++ libary to parse EBML files. Specifications may be rendered at http://matroska-org.github.io/libebml/
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
