name       : libebml
version    : 1.4.0
release    : 9
source     :
    - https://github.com/Matroska-Org/libebml/archive/release-1.4.0.tar.gz : 5ad468d78d21dfcde2901320faad4122ade2a12ecb65ce557b5e15d46671cceb
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A C++ libary to parse EBML files
description: |
    A C++ libary to parse EBML files.
setup      : |
    %cmake . -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
