name       : libebml
version    : 1.3.5
release    : 6
source     :
    - https://github.com/Matroska-Org/libebml/archive/release-1.3.5.tar.gz : efe9851797db47bc78486b6c518d822cfca435afe3d9c9d0812d8e3825cd71e6
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A C++ libary to parse EBML files.
description: |
    A C++ libary to parse EBML files.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
