name       : libebml
version    : 1.3.7
release    : 7
source     :
    - https://github.com/Matroska-Org/libebml/archive/release-1.3.7.tar.gz : b26cf78e9a226bd2a61e032863d8c2fcf3aa96f6e3a7973c93c49303fc31612e
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A C++ libary to parse EBML files
description: |
    A C++ libary to parse EBML files.
setup      : |
    %cmake . -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
