name       : libebml
version    : 1.4.4
release    : 11
source     :
    - https://github.com/Matroska-Org/libebml/archive/release-1.4.4.tar.gz : 3b30d89a5699fef4bdf5b4d7de7a1c94d9be47fababf9caca59250282f051283
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A C++ libary to parse EBML files
description: |
    A C++ libary to parse EBML files.
setup      : |
    %cmake . -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
