name       : libebml
version    : 1.3.4
release    : 2
source     :
    - https://dl.matroska.org/downloads/libebml/libebml-1.3.4.tar.bz2 : c50d3ecf133742c6549c0669c3873f968e11a365a5ba17b2f4dc339bbe51f387
license    : LGPL-2.1
component  : programming
summary    : A C++ libary to parse EBML files.
description: |
    A C++ libary to parse EBML files.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
